# Generated by Django 2.1.dev20180503070829 on 2018-05-21 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinionytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularity',
            name='concept',
        ),
    ]
