# Generated by Django 2.2.dev20180523150237 on 2018-05-24 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinionytics', '0004_polarity_subjectivity_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyWeather',
        ),
        migrations.DeleteModel(
            name='MonthlyWeatherByCity',
        ),
    ]
